---

# based on http://www.eve-ng.net/repo/install-eve.sh

- name: Set qemu-system-x86 options
  lineinfile:
    path: /etc/modprobe.d/qemu-system-x86.conf
    state: present
    regexp: '^options'
    line: 'options kvm_intel nested=1 vmentry_l1d_flush=never'

- name: Install EVE-NG-specific Azure kernel
  apt:
    name: "{{ eveng_azure_kernel_package }}"
    state: latest  # noqa 403
    update_cache: yes
    force_apt_get: yes
  notify: Reboot system
  when: ansible_distribution_major_version == "16"

- name: Set new kernel as default in GRUB
  lineinfile:
    path: /etc/default/grub
    regexp: 'GRUB_DEFAULT=.*'
    line: 'GRUB_DEFAULT="{{ eveng_grub_menu_item }}"'
  notify: Update GRUB
  when: ansible_distribution_major_version == "16"

- name: Configure network interfaces
  template:
    dest: /etc/network/interfaces
    src: etc/network/interfaces-azure
    backup: yes
  notify: Reboot system
  when: ansible_distribution_major_version == "16"

- name: Disable cloud-init network configuration
  copy:
    content: 'network: {config: disabled}'
    dest: /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
  when: ansible_distribution_major_version == "18"
  tags: interfaces

- name: Remove netplan config generated by cloud-init
  file:
    name: /etc/netplan/50-cloud-init.yaml
    state: absent
  when: ansible_distribution_major_version == "18"
  tags: interfaces

- name: Set custom netplan configuration
  template:
    dest: /etc/netplan/50-eveng.yaml
    src: etc/netplan/50-eveng.yaml.j2
  when: ansible_distribution_major_version == "18"
  notify: Reboot system
  tags: interfaces

- name: Check if /etc/network/interfaces is valid
  command: ifup --no-act pnet1
  changed_when: false
  when: ansible_distribution_major_version == "16"
