---
- name: Set TLS certificate config option
  lineinfile:
    path: /etc/apache2/sites-enabled/eveng-ssl.conf
    regexp: '(\s*SSLCertificateFile\s+).*'
    line: '\1/etc/ssl/certs/apache-cert.pem'
    backrefs: yes
  notify: Restart Apache
  tags: tls

- name: Set TLS key config option
  lineinfile:
    path: /etc/apache2/sites-enabled/eveng-ssl.conf
    regexp: '(\s*SSLCertificateKeyFile\s+).*'
    line: '\1/etc/ssl/private/apache-key.pem'
    backrefs: yes
  notify: Restart Apache
  tags: tls
