---
- name: Create Apache SSL virtual server
  template:
    src: etc/apache2/sites-enabled/default-ssl.conf
    dest: /etc/apache2/sites-enabled/default-ssl.conf
  tags: tls
  notify: Restart Apache

- name: Enable redirect to HTTPS
  blockinfile:
    dest: /etc/apache2/sites-enabled/unetlab.conf
    block: |
      RewriteEngine On
      RewriteCond %{HTTPS} !=on
      RewriteRule ^/?(.*) https://%{SERVER_NAME}/$1 [R,L]
    insertbefore: "<Location /html5/>"
  tags: tls
  notify: Restart Apache
