---

- name: Update GRUB
  command: update-grub

- name: Restart MySQL
  service:
    name: mysql
    state: restarted

- name: Restart Apache
  service:
    name: apache2
    state: restarted

- name: Restart EVE-NG license server
  service:
    name: licserver
    state: restarted

- name: Fix EVE-NG permissions
  command: /opt/unetlab/wrappers/unl_wrapper -a fixpermissions

- name: Reboot system
  reboot:

- name: Restart WireGuard
  systemd:
    name: wg-quick@wg0
    state: restarted
